### ISSUE TITLE
Provide easy installation on Julia side via `Pkg.add(URL)` etc

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#200]
Installation for Julia users should be made easier,  ideally allowing them to just type `] add GAP` on the long run.

Of course this raises various technical issues, which we perhaps can describe and discuss here over time. I just wanted to have this issue now as a place holder.

One of the issues is: which GAP to use -- we probably need to / want to build our own (and if we ignore most packages, that's not so hard). Though it'd of course be nice if power users could also use their own GAP (but that's a potential nest of hairy issues).
Also, user's should probably be able to start our "custom" GAP directly, with JuliaInterface loaded.

**Comment by sebasguts** [comment]
This is indeed a delicate issue.

First of all, GAPJulia does not have the structure of a Julia module, and I am not sure if we can achieve this.

Also, the way LibGAP.jl loads its Julia files might not be compatible with the Julia package manager.

Having to compile our own GAP, making it executable, or hooking into a preinstalled one is IMHO a minor issue. Julia build scripts are basically shell scripts, so this can be achieved without any major problems.

**Comment by sebasguts** [comment]
So, the proposal for doing this:

* We move all Julia files from LibGAP.jl into JuliaInterface, except for `initialization.jl`. The files are read in by JuliaInterface anyway, so it does not realy matter.
* We move JuliaInterface and JuliaExperimental into a `pkg` subfolder of GAPJulia, so GAPJulia can be used as a GAP root.
* We then make GAPJulia a proper Julia package, by adding the `.toml`s, providing a build.jl that downloads, builds, and links GAP.
* Since we now know which GAP we use, we can even skip the initialization command, and make `using` this module start GAP.

That way we achieve this package to be a proper Julia package. Please add comments/remarks. I will provide a PR shortly.

**Comment by frankluebeck** [comment]
Cannot the structure be useful as GAP packages and as Julia package at the same time?
For that it would be better to leave the folders  JuliaInterface and JuliaExperimental where they are now (such that the repository can be put in a GAP `pkg` directory, as we did so far). Is it possible to put
a link from `.` to `pkg` on the top level, such that the method with an extra GAP root directory works as well?

When I install julia and GAP with the script [install_julia_gap.sh](https://github.com/oscar-system/GAPJulia/blob/fl_fullinstall/etc/install_julia_gap.sh) the gap directory is about 2.4GB large. Is it possible to allow for an optional argument to Julia's `Pkg.add` which specifies a directory for the GAP installation (by default it would go to `~/.julia/packages/GAP/...`, right?).

**Comment by sebasguts** [comment]
For the second part: Yes, I already implemented it that way here, although I am not yet finished (ETA tomorrow).

For the first part: I think it is actually more useful to have a `pkg` subfolder, that way we could set it as a `GAPROOT`, which is easier than convincing julia to look somewhere else for the package.

**Comment by fingolfin** [comment]
Most of this was resolve by PR #207, we now should take care of issues #208 and #209; in particular, for things to be "easy", they should be documented.

**Comment by sebasguts** [comment]
Done.
