### ISSUE TITLE
Add possibility to add custom GAP packages

### ISSUE THREAD

**Issue by sebasguts** [oscar-system/GAP.jl#246]
By either providing a possibility to add `GAPROOT` paths to GAP or by providing an additional `pkg` folder in `JULIA_DEPOT_PATH`

**Comment by ThomasBreuer** [comment]
If the question is just to extend the list stored in `GAPInfo.RootPaths`
then one can call the GAP function `ExtendRootDirectories`.

Root paths added this way are not considered already when GAP starts,
but this is not relevant from the viewpoint of a Julia user who loads `GAP.jl`
and then wants to load some user specific GAP packages,
because Julia starts GAP with the `-A` option and thus essentially all GAP packages must be loaded by hand.

**Comment by fingolfin** [comment]
I think this is all already possible?
