### ISSUE TITLE
LoadPackage errors

### ISSUE THREAD

**Issue by gangchern** [oscar-system/GAP.jl#247]
When I try to use the JuliaInterface. I try

> GAP.LoadPackage( "JuliaInterface" );
But it returns errors  as following 
```
UndefVarError: LoadPackage not defined

Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at In[28]:1
```

Then I try to compile juliaInterface following the general instructions like 

>  cd <path_to_gaproot>/pkg/GAPJulia/JuliaInterface
> ./configure <path_to_gaproot>
> make

But it also return errors
```
No file Users/gangchen/gap-4.10.1/sysinfo.gap found.

Usage: ./configure [GAPPATH]
       where GAPPATH is a path to your GAP installation
       (The default for GAPPATH is "../../..")

Either your GAPPATH is incorrect or the GAP it is pointing to
is not properly compiled (do "./configure && make" there first).

Aborting... No Makefile is generated.
```

How can I do then? BTW, the gap have been compiled successfully.

**Comment by ThomasBreuer** [comment]
Thank you for your report.

From the paths that show up in your message, it looks as if you are not simply installing `GAP.jl` and its underlying GAP via Julia's package manager,
but you have already an installed version of GAP (compiled with Julia's garbage collector),
*and* you have put the contents of the `pkg` subdirectory of `GAP.jl` into the `pkg` subdirectory of this GAP installation.

If the latter statement is *not* true then the first step to solve the problem is to find the correct <path_to_gaproot>;
for that, start GAP and look at the list `GAPInfo.RootPaths`; one of the entries in that list is the location of a directory that contains the file `sysinfo.gap`, and this path should be taken as `<path_to_gaproot>`.

I would suggest to leave the installation of `GAP.jl` (including `JuliaInterface`) to Julia.
If you really want to use your installed GAP version then start Julia, set Julia's environment variable `ENV[ "GAPROOT" ]` to the `<path_to_gaproot>` as above, and then call `] add https://github.com/oscar-system/GAP.jl`, as described in the README.md.

If this was successful, calling `using GAP` should automatically load the GAP package `JuliaInterface`,
calling GAP's `LoadPackage` is not necessary if the installation of `GAP.jl` works.
(Note that a correct way to load the GAP package `<packagename>` from Julia would be `GAP.Globals.LoadPackage( GAP.julia_to_gap( "<packagename>" ) )`.

**Comment by gangchern** [comment]
Thanks for your kind reply. The problem is solved. 
Now I can use the following to load the package. I meet another problem. How to call the functions in the package? For example, I load the package "toric" 

> GAP.Globals.LoadPackage( GAP.julia_to_gap( "toric" ) )

The output seems correct

```
Loading  Toric 1.9.4 (toric variety package)
by David Joyner (https://sites.google.com/site/wdjoyner/).
Homepage: https://gap-packages.github.io/toric
Report issues at https://github.com/gap-packages/toric/issues
```
Then I try to use the function "InDualCone" in the package

> GAP.Globals.InDualCone([1,-7],[[1,0],[3,4]]);

But it does not work. It throw an error:
```
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `Length' on 1 arguments
```
Could you tell me the correct way to call a function in the package?
Thanks a lot.

**Comment by sebasguts** [comment]
@gangchern As for the `toric` string, you need to convert the input data into GAP objects, i.e., the correct way of calling the function would be
```
GAP.Globals.InDualCone(GAP.julia_to_gap([1,-7]),GAP.julia_to_gap([1 0; 3 4]))
```

**Comment by fingolfin** [comment]
BTW, you can also use `g"bla"` to create GAP string, so to load `toric`, you can also write `GAP.Globals.LoadPackage(g"toric")`

**Comment by fingolfin** [comment]
@gangchern did that resolve your issues?

**Comment by gangchern** [comment]
Hi, thanks for asking. The GAP works well now. 
Cheers
Gang
