### ISSUE TITLE
Travis tests fail with Julia nightly

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#294]
On #293, @ThomasBreuer observed:
> This looks as if, in the case that a Julia package cannot be imported, the first call to `JuliaImportPackage` correctly returns `false` but later calls return `true`.

**Comment by ThomasBreuer** [comment]
To make the "observation" more precise:

When the `read.g` file of `JuliaExperimental` is read into GAP then the messages
```
#I  The Julia package 'Nemo' cannot be loaded.
#I  The Julia package 'Primes' cannot be loaded.
```
belong to the first calls of the function `JuliaImportPackage`, which asks Julia to call its `import` for the given package.
Since the Julia packages cannot be imported, GAP does not read some files which rely on them.

The next call of `JuliaImportPackage` has the argument `"LinearAlgebra"`.
We do not get a message, thus this Julia package gets imported.

In the same `if`` statement, again `JuliaImportPackage` is called with argument `"Nemo"`,
and now we do *not* get a message that Nemo cannot be loaded.
Now Julia has apparently imported Nemo.
How can this happen?

(As a consequence, some GAP code files are read which rely on variables from files which had not been read, hence the later error messages.)

Up to now, I cannot reproduce the behaviour from https://travis-ci.com/oscar-system/GAP.jl/jobs/241031756.

**Comment by fingolfin** [comment]
In addition it is also odd that Nemo is not loaded to boot with -- it should be, and in e.g. the Julia 1.2 test, it is.

I am now building the latest Julia master to see if I can replicate the issue with that locally.

**Comment by fingolfin** [comment]
Reproduced this locally: First, I did `Pkg.add("Nemo")`. This (seemed to) install Nemo in Julia 1.4dev.

But then on a prompt, I can't load it, and this happens:
```
julia> try import Nemo; return true; catch e; return e; end
InitError(:Nemo, ErrorException("cglobal: could not find symbol jl_gc_counted_free"))

julia> try import Nemo; return true; catch e; return e; end
true
```
So, definitely looks like an issue in either Julia or Nemo, or both

**Comment by fingolfin** [comment]
This is actually fixed in Nemo's master branch, see https://github.com/Nemocas/Nemo.jl/commit/08662650c69b8604e4df0129e4ed4b6a845ff56f

So I think we can safely ignore it for now. Of course a new Nemo release with this fix would be nicer.
