### ISSUE TITLE
julia_to_gap handles vectors of Ints differently

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/GAP.jl#315]
```julia
julia> A = Int32[1,2,3]
3-element Array{Int32,1}:
 1
 2
 3

julia> GAP.julia_to_gap(A)
GAP: [ <Julia: 1>, <Julia: 2>, <Julia: 3> ]

julia> GAP.julia_to_gap(A, Val(true)) # the recursive call
GAP: [ 1, 2, 3 ]

julia> GAP.julia_to_gap(Int64.(A))
GAP: [ 1, 2, 3 ]
```

**Comment by fingolfin** [comment]
This is intentional, to ensure round trip fidelity of all types; see https://github.com/oscar-system/GAP.jl/wiki/Rules-for-conversion-between-GAP-and-Julia-objects for details.

Those rules should of course be integrated into the documentation. I started work on this in the distant past, see https://github.com/oscar-system/GAP.jl/pull/203, but it got stalled. Part of the issue was/is that we couldn't really agree/decided whether to use the GAP documentation system, the Julia documentation system, or both (Ideally I'd prefer the latter, except then we should write some tools to make that possible w/o having to duplicate all docs in two places... *sigh*)

**Comment by kalmarek** [comment]
I don't understand the round trip fidelity:
```
GAP.gap_to_julia(GAP.julia_to_gap([1]))
1-element Array{Any,1}:
 1
```
by no means I started with `Int[1]`, got `Any[1]`;
If Julia Int can't fit into Gap Int an `InexactError` should be thrown.

**Comment by kalmarek** [comment]
looking at this again, it's the other way round: if `GapInt` doesn't fit into `Int` the error should be thrown; the other direction is totally fine (as GAP handles them on the fly)

**Comment by fingolfin** [comment]
Sorry for the confusion. I misread the issue, my bad.

What I meant to convey is that converting an Int32 should not (by the original plan, at least) resulting in an (immediate) GAP integer, but rather in a GAP object which wraps the Julia `Int32`, to provide round-trip fidelity. That is indeed exactly what the C part of GAP.jl does.

But `gap_to_julia` and `julia_to_gap` are on a different, higher level, and can do more things. And indeed, `julia_to_gap` converts all Julia integer types to GAP integers. I am actually not that happy about it; but historically, these two functions were quick&dirty helpers that allowed us to get stuff done; they never were intended to be ultimate answer. Part of this is in fact that I was against adding e.g. `convert` methods or constructors before I was sure that we understood the rules for and ramifications of that. Hence it was quite deliberate for this initial code to do something that "sticks out".

Now that things are working, and we (which at this point is a "royal we" I guess; thogh perhaps @ThomasBreuer will help out more with `GAP.jl` and `JuliaInterface`?) have people with Julia experience around, I am happy to investigate other (better?) ways to deal with conversion.

BTW, I've now also added a `conversion` label on GitHub to mark issues which related to conversion.

**Comment by fingolfin** [comment]
You wrote:
> if GapInt doesn't fit into Int the error should be thrown; the other direction is totally fine 

Not sure I understand: do you mean "a nicer error should be thrown" ? Because I already do get an error if I request conversion to `Int`. (Though if you don't specify the target type, then we automatically convert to a BigInt):
```julia
julia> x = GAP.Globals.POW(12,34)
GAP: 4922235242952026704037113243122008064

julia> y = GAP.gap_to_julia(x)
4922235242952026704037113243122008064

julia> typeof(y)
BigInt

julia> GAP.gap_to_julia(Int64, x)
ERROR: MethodError: no method matching MethodError(::String)
Closest candidates are:
  MethodError(::Any, ::Any) at boot.jl:300
  MethodError(::Any, ::Any, ::UInt64) at boot.jl:297
Stacktrace:
 [1] gap_to_julia(::Type{Int64}, ::Main.ForeignGAP.MPtr) at /Users/mhorn/Projekte/OSCAR/GAP.jl/src/gap_to_julia.jl:27
 [2] top-level scope at REPL[21]:1
```

**Comment by kalmarek** [comment]
I meant `InexactError`:
```julia
julia> Int(big(2)^62)
4611686018427387904

julia> Int(big(2)^63)
ERROR: InexactError: Int64(9223372036854775808)
Stacktrace:
 [1] Int64(::BigInt) at ./gmp.jl:358
 [2] top-level scope at REPL[3]:1
```

**Comment by fingolfin** [comment]
@kalmarek that doesn't really answer my question. You already mentioned `InexactError`. What you have not yet said is in which situation you'd like us to use it? Could you perhaps give some concrete you'd like us to treat differently to illustrate what you want?

**Comment by kalmarek** [comment]
```julia
x = 2^62
gx = GAP.julia_to_gap(x)
y = 2*gx ## I assume it's a GAP Integer 
GAP.gap_to_julia(Int, y) # InexactError
```
The `MethodError` You quoted follows basically from wrong usage:
```julia
julia> MethodError("aaa")
ERROR: MethodError: no method matching MethodError(::String)
Closest candidates are:
  MethodError(::Any, ::Any) at boot.jl:300
  MethodError(::Any, ::Any, ::UInt64) at boot.jl:297
Stacktrace:
 [1] top-level scope at REPL[4]:1
```
and has nothing to do with failed conversion

**Comment by fingolfin** [comment]
In your example, GAP.julia_to_gap(x) is actually identical to x:
```
julia> x = 2^62
4611686018427387904

julia> gx = GAP.julia_to_gap(x)
4611686018427387904

julia> x === gx
true
```
This is because small integers in GAP are "immediate" integers. They don't live anywhere in memory, rather, they are stored inside pointers. We can't do that in Julia, though. Hence we have two choices:
1. Add a special Julia type which wraps GAP small integers, something like `struct SmallGapInt  x::Int end` or perhaps `primitive type SmallGapInt <: Integer 64 end` or whatever
2. Map GAP small integers to Julia `Int` and vice versa.

We opted for the latter, because it provides better performance and makes it super convenient to pass small integers to GAP functions.

Of course this also has drawbacks, namely that `GAP.julia_to_gap(12)^GAP.julia_to_gap(34)` is not what you might expect; instead you need to write `@gap(12^34)` to get the GAP big integer equal to 12^34.

Note that adding "GAP integers" on the Julia side is not really something that's a goal here. GAP.jl is intended as a relatively low-level toolbox, on which the actual OSCAR code is built; and for OSCAR, I think we kinda decided that we want to have a single user facing "big integer" type, namely `Nemo.fmpz`.

That said, I am open to exploring adding a `SmallGapInt` type on the Julia side, but we need to keep the pros and cons in sight, and what our ultimate goal is (for me: OSCAR)

**Comment by fingolfin** [comment]
As to the `MethodError`: Actually, it *does* have something with failed conversion: it is triggered by our generic fallback method when it fails to come up with a sensible conversion (but yeah, that code is buggy, and so our attempt to raise a `MethodError` actually raises a different `MethodError`.

I just fixed that; so now you get this error (which is not great either, but slightly better). 
```
julia> GAP.gap_to_julia(Int64, x)
ERROR: Don't know how to convert value of type Main.ForeignGAP.MPtr to type Int64
```
I deliberately did not use `InexactError` here for now, but I'll look into whether that might be a better option for us.

**Comment by fingolfin** [comment]
Current behavior:
```
julia> z = GapObj(big(2)^63-1)
GAP: 9223372036854775807

julia> Int(z)
9223372036854775807

julia> z = GapObj(big(2)^63)
GAP: 9223372036854775808

julia> Int(z)
ERROR: InexactError: Int64(9223372036854775808)
Stacktrace:
 [1] Type
   @ ./gmp.jl:364 [inlined]
 [2] Int64(obj::GapObj)
   @ GAP ~/.julia/packages/GAP/l8YX2/src/constructors.jl:41
 [3] top-level scope
   @ REPL[38]:1
```
