### ISSUE TITLE
problem with JuliaBindCFunction in JuliaInterface

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#349]
When one uses the interface from the GAP side, the GAP function `JuliaBindCFunction` is intended to take a Julia function, create a C-compatible function using `@cfunction`, and then wrap this into a GAP "kernel" function.
Currently this is broken, the examples in `JuliaInterface/example/gap_function_call.gi` run into errors.
```
gap> fun:= JuliaEvalString( "function mysquare( n ) return n^2; end" );
<Julia: mysquare>
gap> cfun:= JuliaBindCFunction( "mysquare", [ "nn" ] );
function( nn ) ... end
gap> cfun( 2 );
Error, MethodError: no method matching ^(::Ptr{Nothing}, ::Int64)
[...]
```

**Comment by fingolfin** [comment]
For now, to avoid any immediate issues, I would avoid `JuliaBindCFunction` and instead use `JuliaFunction`. The idea behind `JuliaBindCFunction` was to provide a optimization. Using the mini-benchmark in `pkg/GAPJulia/JuliaInterface/example/function_perform.gi`, for a trivial toy example the call overhead is reduced by perhaps 20%. Which could matter if you make millions of calls to a Julia function from GAP.



Next, I think we were a bit shortsighted when writing `JuliaBindCFunction` and only tested it with functions that take GAP objects are arguments; I don't think it ever worked for anything that actually did anything interesting with its arguments (i.e., anything beyond just returning the argument(s), or returning a new array containing them, or so). Or perhaps it once did and then semantics changed?!? But I doubt that.

Because the above call to `JuliaBindCFunction` results in this Julia code being invoked: `@cfunction(mysquare, ,Ptr{Cvoid}, (Ptr{Cvoid},))`. But then the argument to `cfun`, which is 2, and which should be passed as an Int64 to Julia, is instead passed as a void pointer. And you can't square a void pointer...

To make this usable, *while preserving the performance advantage*, I think we either need to 
1. insert calls to the C function `julia_gap` into `DoCallJuliaCFunc1Arg`, `DoCallJuliaCFunc2Arg`, ... or,
2. allow the user to specify the desired Julia types for the arguments and the return value.

I just did a quick test, though, and it doesn't seem 1 is enough. Which kinda makes sense: We are asking Julia for a pointer to a C function which specializes the Julia function according to the given types. 

So that leaves option 2, I think. That, or removing this functionality.
