### ISSUE TITLE
Implement support for passing keyword arguments to Julia from the GAP side

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#381]
AFAIK, we currently don't support any way to pass keyword arguments from GAP to Julia, other than to evaluate a string. That should be changed.

**Comment by ThomasBreuer** [comment]
When I discussed this question with @sebasguts , the situation was that `jl_call` simply does not support keyword arguments.
Also `Core._apply` seems to be not suitable for entering keyword arguments.
In order to call
```
Singular.PolynomialRing( Singular.QQ, [ "x", "y" ], ordering = :lex )
```
or
```
Singular.PolynomialRing( Singular.QQ, [ "x", "y" ]; :ordering => :lex )
```
from GAP via the interface, one can define
```
function kwarg_wrapper( func, args, kwargs )
    return func( args...; [ k => kwargs[k] for k in keys( kwargs ) ]... )
end
```
and then the following works.
```
kwarg_wrapper( Singular.PolynomialRing, [ Singular.QQ, [ "x", "y" ] ], Dict( :ordering => :lex ) )
```
JuliaInterface can create all ingredients of this code line, and execute the function call.
Would this be sufficient?

**Comment by fingolfin** [comment]
That would be a good start. Of course i should also be easy to be from GAP. Perhaps we could have a helper there as well which accepts a GAP record for the keyword args. Using that helper then might look something like this on the GAP side (I omitted calls for converting GAP strings and lists to Julia, in order to keep this pseudo example simple):
```
Julia.kwarg_call( Julia.Singular.PolynomialRing, [ Julia.Singular.QQ, [ "x", "y" ] ], rec( ordering := "lex" ) )
```
