### ISSUE TITLE
Release without LinearAlgebra dependency

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/GAP.jl#432]
It would be nice if you could soon make a release without the LinearAlgebra dependency which has already been eliminated in #411.

This would make the `HomalgProject` test run with a released `GAP`.

**Comment by fingolfin** [comment]
A new release is indeed overdue. I'll make one by the end of the week, promise.

But I was *really* hoping to switch to using JLLs in that release, at least for GNU readline, to overcome the buggy readline experience (it's simply completely broken). Not sure why; but the quickest fix seemed to switch to using [Readline_jll](https://github.com/JuliaBinaryWrappers/Readline_jll.jl).

Unfortunately using JLLs has its own share of annoying issues: it works perfectly fine from within Julia, but it causes me major headaches when I want to support starting GAP on its own (and let GAP load Julia), something which is dear to many of us. But to do that, we need to point the GAP binary at the location of the shared libraries it is meant to use (readline, ncurses; more if we want to support packages like ZeroMQInterface, NormalizInterface, etc.). But these paths can change in response to a `Pkg.update()` in Julia: If `Readline_jll` is updated to a newer version, then its binaries are placed into a new directory. E.g. I already have two versions of it:
```
~/.julia/artifacts/9a631b70237f5b99265872c576de736d8e57670f/lib/libreadline.dylib
~/.julia/artifacts/ab99a58fe0fc2d4c9cc03baeda4a82ae0b02a92a/lib/libreadline.dylib
```
Right now, both exist, but on the next `Pkg.gc` run, one might be gone. That means I cannot just put these paths into a shell script and be done. No, I must query Julia for them. But in order to query Julia for them, I must load `Readline_jll`. But I can't just load `Readline_jll`, because it might not be installed in the global Julia environment. There are then some possible ways out of this:

1. I am experimenting with *not* loading GAP, but rather loading Julia + GAP.jl, and then "faking" that this is a plain GAP, see also PR #427. The first 90% of that work were super easy, unfortunately the remaining 90% ;-) are somewhat tricky (more details on that PR):

2. we could assume that GAP.jl is in the global Julia environment (if it is not, then `JuliaInterface` can't load `GAP.jl` and will fail anyway), and load that; at which point we can access `GAP.Readline_jll` to get the desired info. Drawback: we are now effectively loading GAP+Julia twice, more or less doubling the startup time (might still be acceptable as a temporary solution, though)

3. we could decided that it's too risky to rely on GAP.jl being in the global Julia environment, and created a dedicated Julia environment/project for use by GAP.jl; this then could of course have Readline_jll added directly, so that we can just load it; it might even have a Manifest which pins specific versions of Readline_jll etc., so that we can even return to hardcoding paths to the required shared libraries. Drawback: there are lots of things here that are unclear to me; I am not sure if programs are "supposed" to do such a thing, though; and I am wary of pitfalls, and things which are surprising to users, etc.; still it might have potential, so perhaps we should explore this; perhaps also Julia experts like @rfourquet or @kalmarek have some additional insights here

4. something else I can't think of right now (gotta get some sleep)

Also pin @ThomasBreuer  @rbehrends

**Comment by fingolfin** [comment]
Ah what fun: while using Readline_jll fixes readline (see issue #415) for me on macOS, it does not do so on Linux. Grrr.

**Comment by mohamed-barakat** [comment]
> Ah what fun: while using Readline_jll fixes readline (see issue #415) for me on macOS, it does not do so on Linux. Grrr.

It works for me on `plesken`.

**Comment by fingolfin** [comment]
Interesting, it doesn't for me (also on plesken). But perhaps it's time to wipe my .julia (minus 31GB of `artifacts` downloaded for building stuff via BinaryBuilder for Yggdrasil...)

**Comment by fingolfin** [comment]
Nope, doesn't help... @mohamed-barakat when you say "it works": how exactly are you starting GAP then?

**Comment by mohamed-barakat** [comment]
I am very sorry. I ended up starting `.julia/packages/GAP/4od8v/gap.sh`. I will check with the dev version.

**Comment by mohamed-barakat** [comment]
I confirm, it does work on `plesken`.

**Comment by fingolfin** [comment]
So you start it by entering `~/.julia/packages/GAP/4od8v/gap.sh`  ? Could you copy&paste the content of that gap.sh here (I had multiple versions over time, might help me narrow down what's going on).

**Comment by mohamed-barakat** [comment]
Readline worked with this version `GAP.jl`:
```
#!/bin/sh

exec "/home/mo/.julia/packages/GAP/4od8v/gap-4.11.0/gap" -l "/home/mo/.julia/packages/GAP/4od8v/;/home/mo/.julia/packages/GAP/4od8v/gap-4.11.0" "$@"
```

**Comment by mohamed-barakat** [comment]
And also works when I invoke it this way:

```
/home/mo/.julia/dev/GAP/deps/build/gap-4.11.0-julia-1.4/gap -l "/home/mo/.julia/artifacts/848f0f318405266896d24d11e4baf5cf7bf3f203/gap-4.11.0/;/home/mo/.julia/dev/GAP/deps/build/gap-4.11.0-julia-1.4"
```

**Comment by mohamed-barakat** [comment]
I will delete my comments and them again systematically below.

**Comment by mohamed-barakat** [comment]
On MacOS and Linux:

`$ /home/mo/.julia/packages/GAP/4od8v/gap-4.11.0/gap -l "/home/mo/.julia/packages/GAP/4od8v/;/home/mo/.julia/packages/GAP/4od8v/gap-4.11.0"` -> works

MacOS, Gap.jl d3a31f0:

`$ ~/.julia/dev/GAP/deps/build/gap-4.11.0-julia-1.4/bin/gap.sh` -> broken readline

Linux, GAP.jl d3a31f0

`$ ~/.julia/dev/GAP/deps/build/gap-4.11.0-julia-1.4/bin/gap.sh` -> works

**Comment by mohamed-barakat** [comment]
MacOS, GAP.jl bfd980b:

`$(julia -e 'import GAP; print(GAP.gap_exe())')` -> broken readline

Linux, GAP.jl bfd980b:

`$(julia -e 'import GAP; print(GAP.gap_exe())')` -> works

**Comment by fingolfin** [comment]
Yeah, but for me, with `mh/jll` it is simply reverse that.

**Comment by mohamed-barakat** [comment]
This issue can be closed. Right?
