### ISSUE TITLE
problem to load GAP's Browse package

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#456]
With the current master branch of GAP.jl, I tried to install the Browse package,
that is, I go to `~/.julia/artifacts/848f0f318405266896d24d11e4baf5cf7bf3f203/gap-4.11.0/pkg/Browse`, call `./configure /.../GAP.jl/deps/build/gap-4.11.0-julia-1.4; make`,
and then start GAP and enter `LoadPackage( "Browse" );`, with the following error message:
```
#W dlopen() error: libpanel.so.6: cannot open shared object file: No such file\
 or directory
ERROR: LoadError: Error thrown by GAP: Error, module '/.../.julia/artifacts/848f0f318405266896d24d11e4baf5cf7bf3f203/ga\
p-4.11.0/pkg/Browse/bin/x86_64-pc-linux-gnu-julia64-kv7-v1.4/ncurses.so' not f\
ound
```

**Comment by ThomasBreuer** [comment]
The problem can be fixed on the side of the Browse package.
@frankluebeck is working on it.

**Comment by ThomasBreuer** [comment]
Meanwhile @frankluebeck has found a way to change the installation scripts for Browse such that the needed libraries are found at runtime: Add the `GAP_LIBS` path to the `-L` option of `gac`.
We can address this in the next release of Browse.
However, it may be that the same problem affects also other GAP packages, that is, this solution is perhaps not optimal.
Note that one does not get error messages at compile time. For example, running GAP.jl's `deps/BuildPackages.sh` in the relevant `artifacts/.../pkg` directory does not list `Browse` among the (few) failed packages. The problem occurs only at runtime.

With the improved installation scripts, I can install and load Browse, but I have the following problem.
When I call `Browse( CharacterTable( "A5" ) );`, the contents shown on the screen in visual mode looks like this:
```
                             A5
                             ���������������������
                             222...
                             31.1..
                             51..11
                             ���������������������
                             1a2a3a5a5b
                             2P1a1a3a5b5a
                             3P1a2a1a5b5a
                             5P1a2a3a1a1a
                             ���������������������
                             X.111111
                             X.23-1.A*A
                             X.33-1.*AA
                             X.44.1-1-1
                             X.551-1..
```
This means that there is no whitespace inside the panel, and the empty lines are shown as lines of `�`.
@frankluebeck cannot reproduce this problem.
I have already deinstalled and reinstalled GAP and GAP.jl, but the behaviour did not change.

**Comment by fingolfin** [comment]
First off, an unrelated remark: running `BuildPackages.sh` inside the `artifacts` directory in general is not a good idea -- that directory is meant to be immutable. Yes, GAP.jl does it right now if one asks for it, but this is just a temporary hack (and will not work for all packages, as Julia changed all files to read-only in there; due to the way Unix permissions work, though, one can still add new files, which is why some package build systems work).

Next, regarding the visual problems: this may be related to the issue that broke `readline` support: ncurses may not find a suitable terminfo file... This *should* be fixed by us setting the `TERMINFO_DIRS` env variable. At least when one starts GAP via Julia. Can you reproduce the above issue if you start GAP from Julia via `using GAP` and then invoke the Browse command?

Finally, the issue with `libpanel.so.6` not being found should be curable from within GAP.jl, without a need to modify Browse or GAP. It's on my TODO list to work on this, in the context of PRs #413 and #421 but my days are too short *sigh*

**Comment by fingolfin** [comment]
Looking at https://packages.ubuntu.com/search?suite=default&section=all&arch=any&lang=de&keywords=julia&searchon=namesit seems `libjulia-dev` is what you need

**Comment by ThomasBreuer** [comment]
@fingolfin Thanks.
Yes, the visual problems arise when I start Julia, enter `using GAP; GAP.prompt()`, and then call `Browse( CharacterTable( "A5" ) );` at the GAP prompt.
The environment variable `ENV[ "TERMINFO_DIRS" ]` is set after `using GAP` (or earlier if I set it already before starting Julia, the effect is the same in both situations).
Without this environment variable, one gets an error message already when one loads Browse.

As I wrote, Frank cannot reproduce this problem, thus something must be wrong with my setup. What can I do beyond deinstalling (remove the artifacts contents, `Pkg.rm( "GAP" )`) and then reinstalling GAP (`Pkg.develop( ... )`, `Pkg.build( "GAP" )`, compile Browse)?

**Comment by ThomasBreuer** [comment]
@fingolfin Thanks for the hint about libjulia-dev.
This library is not available for my Ubuntu 18.04, but the problem is gone with Ubuntu 20.04.
If we regard this as a solution then the issue can be closed.

**Comment by frankluebeck** [comment]
I can reproduce the visual problems in Ubuntu 18.04, there is no such problem in Ubuntu 20.04 or in Debian 10. I have no idea what causes the difference. 

Setting `TERMINFO_DIRS` to the system default terminfo path before starting julia causes that GAP (with Browse) cannot be loaded. Otherwise this variable is correctly set to the libinfo directory inside julia's GAP  installation, and then Browse can be loaded.

My experimental fix to make Browse work in a GAP within julia (except for the mentioned visual problem) is to add the content of `GAP_LIBS` from `sysinfo.gap` to the linker options; this way the executable in the Browse package gets an `rpath` entry and finds the needed libraries at runtime.

An alternative solution would be that julia (and so GAP within julia) is started by a script that sets the `LD_LIBRARY_PATH` variable appropriately. Wouldn't that be a better solution which would also work for other packages?

**Comment by fingolfin** [comment]
After just having issues related to this again and a discussion with @ThomasBreuer , some notes (so I don't forget it again):

- we ought to make sure Browse's `ncurses.so` is compiled and linked against the correct ncurses shared library
- we can do so by setting suitable environment variables, I guess, before compiling it
- of course even better would be to provide a precompiled version via ` GAP_browse_jll` or so (see issue #614)
- I've just encountered the error "Error opening terminal: xterm-256color" again, while trying to load `Browse`; I fixed this by entering `ENV["TERMINFO_DIRS"] = joinpath(GAP.GAP_jll.Readline_jll.Ncurses_jll.find_artifact_dir(), "share", "terminfo")` ; this is what GAP.jl does before loading GAP -- but it intentionally only does this temporarily, for the duration of the GAP initialization. So if Browse is not loaded during the GAP initialization, this doesn't work. I discussed this with @ThomasBreuer, here are some options to deal with this:
  1. we just set `ENV["TERMINFO_DIRS"]` globally in GAP.jl: easy, fixes the issue reliably; but may cause problems for other people and packages, as we modify the global environment. For now, this is only a hypothetical issue, though
  2. variant of 1: do the same, but only if `TERMINFO_DIRS` is not already set (this way, at least people can enforce a custom `TERMINFO_DIRS` if they need to; but now things will fail for a different subset
  3. Similar to 1. (or 2.), but instead of GAP.jl, the env var is set by `ncurses_jll` -- this is also proposed in https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/687 and has similar pros/cons, but at least it'd be done consistently for all packages using `ncurses_jll`
  4. We hack the GAP function `LoadDynamicModule` (i.e., replace it with our own, which calls the original, but only after temporarily setting certain environment variables suitably): that limits the impact, and *should* work, but of course is quite a hack
  5. Modify Browse to look for an env var `JULIA_TERMINFO_DIRS`, and if present, somehow use that instead of `TERMINFO_DIRS` (of course then GAP.jl also needs to set `JULIA_TERMINFO_DIRS`). Not sure if that's even possible, though, and requires coordinated changes for Browse and GAP.jl, so bit of a hassle
  6. ... ?

Right now, I tend to prefer option 5 (I won't have time to implement it for now, but if somebody wants to give it a go, please don't hesitate).  I am also looking into option 3 (as it was requested by Julia devs anyway, and trying to get that in might be a good opportunity to get other people to chime in on this).

**Comment by mohamed-barakat** [comment]
Option (5) would need a new release of `Browse`. Option (3) seems like a good intermediate solution, with no need to reverse it even if `Browse` implement option (5). Right?

**Comment by fingolfin** [comment]
I just tried `GAP.Packages.install("browse")` with GAP.jl 0.6, and it seemed to work fine.

@ThomasBreuer can this be closed, or is there any remaining issue?

**Comment by ThomasBreuer** [comment]
I can confirm that `GAP.Packages.install("browse")` installs the package, that the package can be loaded afterwards, and that it works.
