### ISSUE TITLE
GAP.Globals.Display vs GAP.Display

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/GAP.jl#457]
The two methods `GAP.Globals.Display` and `GAP.Display` behave differently. The latter prints one more newline. Are they meant to be different and which one should be used?

```julia
julia> using GAP

julia> a = GAP.Globals.String( 1 )
GAP: "1"

julia> GAP.Globals.Display( a )
1

julia> GAP.Display( a )
1


julia>
```

**Comment by ThomasBreuer** [comment]
Thanks for this observation.
The reason for the visible difference is that `GAP.Display` calls Julia's `println` with a string that contains already a trailing newline character.
I think we should fix this by calling `print` instead of `println`, I will create a pull request for that.

Logically, the two functions differ in the sense that Julia prints the output in the case of `GAP.Display` whereas GAP prints the output in the case of `GAP.Globals.Display`.
However, this should not lead to visible differences.
(For example, also the output in Jupyter notebooks should be equal.)

**Comment by fingolfin** [comment]
Thanks for the PR. But Mohamed still posed a good question:
> Are they meant to be different and which one should be used

If we keep GAP.Display, we should ponder some things:
1. What *is* it for, and for whom?
2. If the only purpose is that we want to print via Julia routines instead of GAP routines, wouldn't we be better of patching GAP so that all its printing goes through Julia? This would possibly also help the Jupyter integration. Seems like something we ought to do anyway (is there an issue for this already? If not, let's create one)
3. Its name is of course reassuring for GAP veterans; but also confusing for people coming from Julia, where there is a `display` function that has a similar name but is quite different
4. If we keep it, should we document it? (Depends on the answer to 1, I think)
5. If we keep it, can / should we add some tests?
