### ISSUE TITLE
Suppress output of `GAP.Packages.install` if package is already installed?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#476]
If one needs a package like "ferret" inside Julia code, one may want to call `GAP.Packages.install("ferret")` to ensure it is available; the operation is essentially idempotent, so this is fine. However, it outputs text which is visible to the user, which is not nice:
```
julia> GAP.Packages.install("ferret")
#I  Getting PackageInfo URLs...
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/ferret/PackageInfo.g ...
#I  The newest version of package "ferret" is already installed
true
````

**Comment by ThomasBreuer** [comment]
The info messages in question are created by PackageManager if the info level of `InfoPackageManager` is at least 3, which is the default value.
If the point is to avoid the messages then we could set the level to 2 in the Julia code, or even to a smaller value.

However, if the point is to make sure that *some* version of the package is available, calling PackageManager's `InstallPackage` is not what one wants, since it will download the newest `PackageInfo.g` in order to make sure that the *newest* version of the package is installed.
Perhaps a function `GAP.Packages.load_and_install_if_necessary`  would be a better solution, which tries to install the package only if it cannot simply be loaded, and signals an error if the package cannot be installed.

**Comment by ThomasBreuer** [comment]
@fingolfin Can this issue be closed?
