### ISSUE TITLE
Error thrown by GAP: Error, PackageManager: InstallPackage: <string> must be a string

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/GAP.jl#499]
After updating to GAP.jl#af58b98 and rebuilding `HomalgProject` I get the following error:

```julia
              _
  _       _ _(_)_     |  Documentation: https://docs.julialang.org
 (_)     | (_) (_)    |
  _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
 | | | | | | |/ _` |  |
 | | |_| | | | (_| |  |  Version 1.4.1 (2020-04-14)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using HomalgProject
ERROR: InitError: Error thrown by GAP: Error, PackageManager: InstallPackage: <string> must be a string

Stacktrace:
[1] error(::String, ::String) at ./error.jl:42
[2] error_handler() at /Users/mo/.julia/dev/GAP/src/GAP.jl:157
[3] call_gap_func(::Main.ForeignGAP.MPtr, ::Main.ForeignGAP.MPtr; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/mo/.julia/dev/GAP/src/ccalls.jl:213
[4] call_gap_func at /Users/mo/.julia/dev/GAP/src/ccalls.jl:203 [inlined]
[5] #_#6 at /Users/mo/.julia/dev/GAP/src/ccalls.jl:226 [inlined]
[6] (::Main.ForeignGAP.MPtr)(::Main.ForeignGAP.MPtr) at /Users/mo/.julia/dev/GAP/src/ccalls.jl:226
[7] __init__() at /Users/mo/.julia/dev/HomalgProject/src/HomalgProject.jl:164
[8] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
[9] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:781
[10] _require(::Base.PkgId) at ./loading.jl:1006
[11] require(::Base.PkgId) at ./loading.jl:927
[12] require(::Module, ::Symbol) at ./loading.jl:922
during initialization of module HomalgProject
```

**Comment by mohamed-barakat** [comment]
Commit af58b98 causes the regression.

**Comment by fingolfin** [comment]
What does line `src/HomalgProject.jl:164` look like (from the above stack trace)?

**Comment by mohamed-barakat** [comment]
The first line of:
```julia
    GAP.Globals.EnhanceRootDirectories(julia_to_gap([julia_to_gap(
        HOMALG_PROJECT_PATH * "/",
    )]))
```

**Comment by ThomasBreuer** [comment]
When I insert a `print` statement in the `__init__` function of HomalgProject such that `GAP.Globals.NameFunction( GAP.Globals.EnhanceRootDirectories )` is shown, I see `GAP: "InstallPackage"` at runtime before the error message appears.
Somehow the administration of GAP's global variables gets corrupted.
(`EnhanceRootDirectories` gets bound when the file `Tools.g` of HomalgProject is read.)

**Comment by fingolfin** [comment]
Weird. For me it actually dies in another place, in `DownloadPackageFromHomalgProject`, complaining about `GAP.Globals.PKGMAN_Exec` being undefined.... to analyze this further, I inserted this code:
```julia
    @show GAP.GVarName("PKGMAN_Exec")
    @show GAP._ValueGlobalVariable("PKGMAN_Exec")
    @show GAP.ValueGlobalVariable("PKGMAN_Exec")

    @show GAP.GVarName(:PKGMAN_Exec)
    @show GAP._ValueGlobalVariable(:PKGMAN_Exec)
    @show GAP.ValueGlobalVariable(:PKGMAN_Exec)

    @show GAP.Globals.PKGMAN_Exec
```
and the result is:
```
GAP.GVarName("PKGMAN_Exec") = 0x0000000000003a25 # WRONG
GAP._ValueGlobalVariable("PKGMAN_Exec") = Ptr{Nothing} @0x000000012e0e15b0  # CORRECT
GAP.ValAutoGVar(GAP.GVarName("PKGMAN_Exec")) = Ptr{Nothing} @0x0000000117e148f0 # WRONG
GAP.ValueGlobalVariable("PKGMAN_Exec") = GAP: function( dir, cmd, args... ) ... end  # CORRECT

GAP.GVarName(:PKGMAN_Exec) = 0x0000000000003a25 # WRONG
GAP._ValueGlobalVariable(:PKGMAN_Exec) = Ptr{Nothing} @0x0000000117e148f0 # WRONG
GAP.ValAutoGVar(GAP.GVarName(:PKGMAN_Exec)) = Ptr{Nothing} @0x0000000117e148f0 # WRONG
GAP.ValueGlobalVariable(:PKGMAN_Exec) = GAP: fail # WRONG

GAP.Globals.PKGMAN_Exec = GAP: fail # WRONG
```
Removing the `@pure` annotation from `GVarName` fixes the problem for me.

However, I am still somewhat confused... So first off, after the test failed, I checked and it turns out the value of `GVarName` reported above is WRONG in both cases (the correct value turned out to be `0x0000000000003a34`). The wrong value `0x0000000000003a25` actually indeed refers to a variable which is set to `fail`... which is why I find it even more flabbergasting that in two cases above, we somehow get the *correct* result after all...?!?).

Anyway, so first I thought that perhaps the call(s) to `GVarName` are being moved too much up, perhaps to before even libgap is loaded; but that can't be right, as we actually get a somewhat sensible result from it, just note the one we'd expect...

Next I modified `GVarName` to print some debugging info (yeah yeah, a pure function shouldn't print anything, but as long as it works... ;-). I used this:
```julia
# for debugging
function NameGVar(gvar::Csize_t)
    ccall(:NameGVar, Any, (Csize_t,), gvar)
end

Base.@pure function GVarName(name::Union{AbstractString,Symbol})
    gvar = ccall(:GVarName, Csize_t, (Ptr{UInt8},), name)
    println("GVarName($name) = $gvar, which maps back to ", CSTR_STRING(NameGVar(gvar)))
    return gvar
end
```
With this in place, I see this when doing `using 
```
...
GVarName(CompareVersionNumbers) = 1596, which maps back to CompareVersionNumbers
GVarName(InstallPackage) = 14884, which maps back to InstallPackage
GVarName(PKGMAN_Exec) = 14885, which maps back to PKGMAN_Exec
GVarName(PKGMAN_Exec) = 14885, which maps back to PKGMAN_Exec
GVarName(PKGMAN_Exec) = 14885, which maps back to PKGMAN_Exec
GVarName(PKGMAN_Exec) = 14885, which maps back to PKGMAN_Exec
GVarName(PKGMAN_Exec) = 14885, which maps back to PKGMAN_Exec
GVarName(NameFunction) = 1507, which maps back to NameFunction
...
GVarName(InstallPackage) = 14884, which maps back to InstallPackage
GAP.GVarName("PKGMAN_Exec") = 0x0000000000003a25
GVarName(PKGMAN_Exec) = 14900, which maps back to PKGMAN_Exec
GAP._ValueGlobalVariable("PKGMAN_Exec") = Ptr{Nothing} @0x0000000130cd9710
GAP.ValAutoGVar(GAP.GVarName("PKGMAN_Exec")) = Ptr{Nothing} @0x000000010f2bc8f0
GVarName(PKGMAN_Exec) = 14900, which maps back to PKGMAN_Exec
...
```
Afterwards, I get this interactively:
```
julia> GAP.NameGVar(UInt(14885))
GVarName(StringViewObj) = 14867, which maps back to StringViewObj
GAP: "DownloadURL"

julia> GAP.NameGVar(UInt(14900))
GAP: "PKGMAN_Exec"
```

So it really looks as if the value of `GVarName(:PKGMAN_Exec)` changed over time -- which confuses me endlessly, as that would break all kinds of things, starting with the interpreter, which implements all access to global variables via `GVarName` -- in particular, in the abstract syntax trees produced by the GAP coder, we don't store the names of the global vars as a string; rather, we only store the output of `GVarName`. If that changed those mappings, all previously coded functions containing references to the "moved" objects in the hahstable would be broken.

If anybody has an idea (@rbehrends ?) please let me now.


Ultimately, if we can't fix this, it'd mean we have to drop the nice @pure optimization again :-/.

**Comment by fingolfin** [comment]
I augmented my printing to also show the process id, and that solved the mystery, I think:
```
GVarName(PKGMAN_Exec) = 14885, which maps back to PKGMAN_Exec in thread 1 of process 43274
...
GVarName(PKGMAN_Exec) = 14900, which maps back to PKGMAN_Exec in thread 1 of process 42958
```
So, yeah, in different processes we might end up with different gvar ids; simply because permuting the order in which we invoke `GVarName` will also affect the values it returns.

The reason two processes are involved here is, I think, precompilation. So ultimately, the issue is that, Julia requires even more of `pure` functions than GCC does: that they return the same value even across multiple process runs. So e.g. `getpid()` is "pure" under the GCC definition, but is not pure under the Julia definition.

That's a bummer. I may have to remove the `@pure` optimization again :-(

**Comment by ThomasBreuer** [comment]
The documentation of `Base.@pure` says: "This macro [...] may be subject to changes."
I read this as "Better do not use this macro".

**Comment by rfourquet** [comment]
> I read this as "Better do not use this macro".

Yes this is exactly how the core devs intend this docstring to be read. There is a running joke about how only Jameson knows how to use this macro properly. 

I wonder if one solution to keep using `@pure` would be to duplicate the concerned functions: one set which is used mainly/only during precompilation (without `@pure`), and one set of `@pure` functions which we are sure are not used during precompilation. But that seems very brittle and complicated to maintain.
