### ISSUE TITLE
problem to load GAP.jl 0.4.3 in Julia 1.3.1

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#509]
(see the discussion for oscar-system/Oscar.jl/pull/144)

@rbehrends @fingolfin Perhaps you know immediately what is wrong with GAP.jl 0.4.3.
When I install Julia 1.3.1 and enter
```
using Pkg; Pkg.add( PackageSpec(name="GAP", version="0.4.3"))
```
then `using GAP` runs into an error:
```
ERROR: InitError: ccall: could not find function julia_gap
Stacktrace:
 [1] _GAP_TO_JULIA at /home/sam/.julia/packages/GAP/tkivN/src/ccalls.jl:16 [inlined]
 [2] getproperty at /home/sam/.julia/packages/GAP/tkivN/src/ccalls.jl:350 [inlined]
 [3] lastindex(::Main.ForeignGAP.MPtr) at /home/sam/.julia/packages/GAP/tkivN/src/adapter.jl:114
 [4] evalstr(::String) at /home/sam/.julia/packages/GAP/tkivN/src/ccalls.jl:64
 [5] reset_GAP_ERROR_OUTPUT() at /home/sam/.julia/packages/GAP/tkivN/src/GAP.jl:142
```
There is no such problem with GAP.jl 0.4.2 or with the current master branch of GAP.jl.

**Comment by rbehrends** [comment]
I had to dig into the functioning of `Libdl` the past couple of days for unrelated reasons, so I may have an idea as to what causes the issue. I'll note that I cannot reproduce that on either macOS or Linux myself (using Julia 1.3.1 with a fresh Julia environment), so there is probably more to the issue than meets the eye, possibly some other 

One difference between Julia on macOS and Linux are the [the default flags of `Libdl.dlopen()`](https://docs.julialang.org/en/v1/stdlib/Libdl/), which include `RTLD_GLOBAL` on macOS and to `RTLD_LOCAL` on Linux. It looks like `JuliaInterface.so` is now loaded via `Libdl.dlopen()` with the default flags from Julia rather than via GAP's dynamic package loader (I think). I suspect that this results in the symbols from `JuliaInterface.so` not showing up in the global namespace, and so `ccall()` cannot find it. Now, `JuliaInterface.so` seems to be also loaded from `JuliaInterface`'s `init.g`, and this time with `RTLD_GLOBAL`, so there may be something else going here (maybe the order of `dlopen()` calls matters?). I think we should explicitly supply the flags in `GAP.jl`, anyway, even if it doesn't fix the issue, as we want consistent behavior across platforms.

**Comment by ThomasBreuer** [comment]
@rbehrends thanks.
What I found most irritating is that there is no problem with Julia 1.3.1 and the GAP.jl master branch.
I have tried to inspect this further, but now I cannot reproduce the error with Julia 1.3.1 and GAP.jl 0.4.3 anymore; also removing GAP.jl's directory from ~/.julia/packages (forcing a new build of GAP.jl) does not help. What else can I do in order to get the error back?

**Comment by fingolfin** [comment]
Unfortunately I cannot reproduce this issue locally, which makes it kinda hard to debug. I tried both on macOS and Linux. Note that on Travis, it *does* appear on both of those systems! See e.g. https://travis-ci.com/github/oscar-system/Oscar.jl/builds/179198599

Perhaps it's only on specific systems? Perhaps only if some other software is installed / not installed? Compiler or kernel versions? Weird...

**Comment by fingolfin** [comment]
If anybody can reproduce this locally, can you try commenting out the line `global JuliaInterface_handle = Libdl.dlopen(JuliaInterface_path)` in src/GAP.jl to see if that helps?

Also, it'd be great to learn the precise OS (e.g. which Linux distro) to see if I can find a similar system; and/or if somebody knows a system where this is reproducible and into which I could SSH...

**Comment by ThomasBreuer** [comment]
I have tried a completely new installation of Julia 1.3.1:
Start with an empty `~/.julia` directory, unpack the julia archive, start Julia, add the package GAP, and then enter `using GAP`;
but I cannot reproduce the error anymore on my notebook.

(The error still happens on Travis: I had updated oscar-system/Oscar.jl/pull/144, and the same error message appears as before.)

**Comment by fingolfin** [comment]
@rbehrends if you can reproduce this somewhere, is there a way I can get SSH access to that system to debug it? I should now have some limited time for this again.

If we can't figure this soon, I suggest we just mark tests using Julia 1.3.1 as "allowed to fail" *for the time being*, and focus on Julia 1.4 and 1.5; of course we should still understand and ideally resolve the issue with 1.3, but this isn't a major priority (long term we will target Julia 1.6 anyway).

**Comment by rbehrends** [comment]
See my [recent PR for GAP.jl](https://github.com/oscar-system/GAP.jl/pull/512). This fixes the situation on Linux, but exposes a different problem on macOS. However, the macOS problem exists anyway; that we haven't encountered it seems to be the result of implementation-defined behavior, which we should not rely on. Importantly, with the PR, this becomes an easily reproducible problem.

**Comment by rbehrends** [comment]
Writing this up in detail actually prompted me to look more closely at the remaining issue on macOS. It turns out that two different versions of `JuliaInterface.so` from two different paths were being loaded. By making sure that the same file is used both when the GAP kernel loads it and when GAP.jl loads it fixes the remaining problem.

**Comment by mohamed-barakat** [comment]
Excellent Reimer :)

**Comment by fingolfin** [comment]
Good news, I can now reproduce this on plesken, a Linux machine. It was quite simple, actually (in fact I feel stupid for not trying that sooner, given the evidence *facepalm*):
```
$ cd Oscar.jl
$ julia-1.3 --project=proj-1.3 # create a fresh project
...
(proj-1.3) pkg> dev .
...
julia> using Oscar
[ Info: Precompiling Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13]
[ Info: Generating module common
[ Info: Generating module ideal
[ Info: Generating module graph
[ Info: Generating module fulton
[ Info: Generating module fan
[ Info: Generating module group
[ Info: Generating module polytope
[ Info: Generating module topaz
[ Info: Generating module tropical
[ Info: Generating module matroid
ERROR: LoadError: InitError: ccall: could not find function GAP_EvalString
Stacktrace:
 [1] evalstr_ex at /Users/mhorn/.julia/packages/GAP/tkivN/src/ccalls.jl:36 [inlined]
...
```

I'll investigate PR #512 and alternatives fixes now.
