### ISSUE TITLE
Automatically convert Julia strings into GAP strings

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/GAP.jl#523]
It would be quite convenient if Julia strings are automatically converted during GAP function calls to GAP strings, i.e., if the current default behavior

```julia
julia> gapfunc(obj, "x") ## "x" is passed as a Julia string and causes an error
error, no method found
julia> gapfunc(obj, g"x") ## "x" is passed as a GAP string
success
```

 could be changed to

```julia
julia> gapfunc(obj, "x") ## "x" is passed as a GAP string
success
julia> gapfunc(obj, j"x") ## "x" is passed as a Julia string ON PURPOSE and causes an error
error, no method found
```

**Comment by fingolfin** [comment]
The problem with that idea is that it doesn't really help with the performance issue (mostly extra GC stress): in your second code variant, we *always* either convert the string (first case) or else must create a temporary wrapper object, just to avoid the conversion. Well, OK, in theory, if one codes this very carefully, one might be able to arrange it so that the Julia compiled can avoid materializing that wrapper object, and only use its "virtual existence" to control method dispatch selection. But that sounds like a quite fiddly undertaking, and it's not even completely clear to me whether it is possible. Someone (ideally the people who want this, i.e., you or one of your coworkers) should at least prepare a proof-of-concept prototype to establish that this is possible.

Another alternative solution for your would be to add a `T_JULIA_STRING` wrapper type to JuliaInterface (resp. to allow `T_JULIA` to have multiple GAP type objects associated) so that wrapped objects gets the `IsStringObj` filter, and then allow accessing this fake GAP string objects transparently from GAP. There are some hurdles to take here, too (e.g. Julia doesn't really offer bytewise objects to its unicode strings, but rather access to UTF codepoints; that doesn't matter for plain ASCII strings, but it does once you go beyond ASCII; we can patch over this, it just means that there is some non-trivial work involved). 


But for this discussion, it would be super helpful to know your *actual* usecase. That might give me some extra ideas (I had some when we talked but I am not sure I 100% understood the problem)

**Comment by fingolfin** [comment]
@mohamed-barakat if you are still interested in that, an answer to my (implied) questions above would be good: most importantly, knowing some actual *concrete* use cases would be helpful.
