### ISSUE TITLE
inconsistent handling of null characters in strings in GAP and Julia

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#527]
Null characters seem to be allowed in Julia strings.
```
julia> str = "abc\000def"
"abc\0def"

julia> length( str )
7

julia> str[4]
'\0': ASCII/Unicode U+0000 (category Cc: Other, control)

julia> println( str )
abcdef
```
The conversion to GAP cuts the string at the first null character.
(Is this a bug or a feature?)
```
julia> gstr = GAP.julia_to_gap( str )
GAP: "abc"

julia> GAP.Globals.Length( gstr )
3

```
GAP itself seems to have problems with null characters in strings.
(Is this a bug or a feature?)
```
gap> s:= "abc\000def";
"abc\000def"
gap> Length( s );
7
gap> Print( s, "\n" );
abc
```
Another inconsistency:
GAP supports [the notation `\0xYZ`, with hex digits `Y` and `Z`](https://www.gap-system.org/Manuals/doc/ref/chap27.html#X82E5F5AB818F32DB), the GAP string `"\0xYZ"` has length 1.
The Julia string `"\0xYZ"` consists of a null character followed by `"xYZ"`.

**Comment by fingolfin** [comment]
The conversion to GAP which cuts the string is a bug. GAP is supposed to work fine with strings that contain null bytes. 

Printing strings with null bytes is not quite well-defined, though -- so one can certainly quibble about whether the way GAP prints them is buggy or not. But I am convinced it is not intentional (so I'd not argue against calling it a bug!). Indeed, this is because at the lowest level, GAP does all its printing via the C function `FormatOutput`, and that turns even string objects into C strings which it assumes are null terminated. Hence it aborts early here. (And if GAP wasn't super careful to always null terminate its string objects, we might also end up printing garbage for some of them... arguably that's another facet of the "bug" in `FormatOutput`). 

Regarding the GAP notation `\0xYZ`, I don't know how to resolve that. But it seems less important than dealing with, say, `\n`.

**Comment by ThomasBreuer** [comment]
@fingolfin Thanks for the feedback.
The conversion to GAP just calls libgap's `GAP_MakeString`.
My interpretation of GAP's file `src/stringobj.h` is that one would have to call GAP's `MakeStringWithLen` in order to create a string that can contain null characters, but this function cannot be accessed via libgap.
So what is a suitable way to fix the problem: first extend libgap and then use the new function in GAP.jl, or just add the missing C function to GAP.jl?

Concerning the printing problem in GAP, I have created a GAP issue.

Concerning GAP's `\0xYZ` notation, I think that since something like `"\0x00"` is a valid Julia string, the `@g_str` macro should catch this case, and replace it by `\000x00`.
(On the other hand, one can argue that this format is a very exotic case that can be documented in GAP.jl as an exception, then the overhead for the macro can be avoided. Anyhow the macro is not perfect.)

**Comment by fingolfin** [comment]
We can actually call `MakeStringWithLen` right now; it just isn't on the list of functions explicitly under the stability guarantees provided by things in libgap. But since we control GAP, we are safe to use it (`MakeStringWithLen` won't go away, I can promise that). We already are calling a bunch of other things outside the libgap guarantee. (For some of them, it'd make sense to eventually add them to libgap, too; but for others, this is me taking advantage of GAP kernel internals that probably never will be put under the libgap umbrella)

**Comment by ThomasBreuer** [comment]
@fingolfin Thanks.
I will create a pull request for GAP.jl
(and also one for GAP, concerning the extension of libgap; I think it is better to make such guarantees explicit --I would never have dared to state that I control GAP).

**Comment by ThomasBreuer** [comment]
The problem in Julia is solved now, and the printing question for GAP is documented via a cross-referencing issue for GAP.
Thus this issue can be closed.
