### ISSUE TITLE
Downloading gap artifact generates 404

### ISSUE THREAD

**Issue by albinahlback** [oscar-system/GAP.jl#598]
I think it still manage to download, but something generates 404. I haven't been able to see causes it.
```
(@v1.5) pkg> dev GAP.jl/
Path `GAP.jl/` exists and looks like the correct package. Using existing path.
  Resolving package versions...
Downloading artifact: gap
curl: (22) The requested URL returned error: 404
Downloading artifact: gap
##########                                                                14,4%##O=##
```

**Comment by fingolfin** [comment]
Thank you for taking the time to report this. However, there is really nothing we can do about this: the file being downloaded is hosted on GitHub, so any unexpected 404 error is due to GitHub having a (hopefully temporary) issue, and/or something  on the network is having an issue (e.g. your ISP, firewall, etc.). Moreover, the download is performed by Julia, so we have no control over that in any way either (e.g. to force a retry or something like that).
