### ISSUE TITLE
Better gap.sh support

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#611]
Right now we have this code in `src/setup.jl` which generates a `gap.sh` so that people can invoke GAP "as usual" (although in the background this starts Julia load GAP.jl and then opens a GAP prompt).
```julia
        ##
        ## Create Project.toml & Manifest.toml for use by gap.sh
        ##
        @info "Generating custom Julia project ..."
        relative_pkgdir = joinpath("..", "..")
        @assert abspath(gaproot_mutable, relative_pkgdir) == gaproot_gapjl
        run(pipeline(`$(Base.julia_cmd()) --startup-file=no --project=$(gaproot_mutable) -e "using Pkg; Pkg.develop(PackageSpec(path=\"$(relative_pkgdir)\")); Pkg.resolve()"`))
```

However, this slows down package precompilation and still is inflexible: in order to use that `gap.sh`, people need to either launch Julia, load GAP.jl, call `gap_exe` then execute the resulting path (thus loading GAP *twice*, for twice the overhead); or they need to add a symlink somewhere, which they then need to potentially update all the time.

So I think we need something better, I am just not yet quite sure *what*... Here's one idea: We add a function which uses can call and which places a "fake gap.sh" in a place of their choice, along with the  `Project.toml` as generated by the code I quoted above (perhaps hiding it away somewhere?). Then it is less black magic and more explicit. And we can remove anything related to it from precompilation.

Thoughts? Alternative ideas? @mohamed-barakat @ThomasBreuer

**Comment by ThomasBreuer** [comment]
Up to now, I have used the symlink variant, that is, I have created an `alias` pointing to the `gap.sh` in question.
The path encodes the location of `GAP.jl` (which does not change except if the user decides to change it) and the Julia version number (o.k., this changes sometimes, but not very often).

The classical GAP user gets the `gap.sh` by calling `./configure; make` after unpacking the GAP archive.
Users of GAP via Julia will install GAP by first installing and starting Julia and then calling something like `using Pkg; Pkg.add("GAP")`. Afterwards they can start GAP inside Julia via `GAP.prompt()`. I think that explicitly calling another Julia function in order to create `gap.sh`, as an optional part of the GAP installation, would be fine.

**Comment by mohamed-barakat** [comment]
> The path encodes the location of `GAP.jl` (which does not change except if the user decides to change it)

Are you assuming the path `~/.julia/dev/GAP`? Because otherwise, it changes whenever `GAP.jl` is updated.

**Comment by mohamed-barakat** [comment]
> So I think we need something better, I am just not yet quite sure _what_... Here's one idea: We add a function which uses can call and which places a "fake gap.sh" in a place of their choice, along with the `Project.toml` as generated by the code I quoted above (perhaps hiding it away somewhere?). Then it is less black magic and more explicit. And we can remove anything related to it from precompilation.

I like this idea very much of allowing the user to decide where to install `gap.sh`.  The user has then the ability to choose a path that doesn't change when Julia or `GAP.jl` are updated.

**Comment by fingolfin** [comment]
This has been done in PR #678 which added `GAP.create_gap_sh(dstdir::String)`
