### ISSUE TITLE
ConfluentMonoidPresentationForGroup

### ISSUE THREAD

**Issue by fieker** [oscar-system/GAP.jl#639]
```
ERROR: Error thrown by GAP: Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `IsomorphismFpGroupByChiefSeries' on 2 arguments at /home/fieker/.julia/artifacts/8dd2012d4ef66568b7667a066059847825d8a1f2/share/gap/lib/methsel2.g:249 called from
IsomorphismFpGroupByChiefSeries( G, "F" ) at /home/fieker/.julia/artifacts/8dd2012d4ef66568b7667a066059847825d8a1f2/share/gap/lib/gpfpiso.gi:48 called from
IsomorphismFpGroupByChiefSeries( G ) at /home/fieker/.julia/artifacts/8dd2012d4ef66568b7667a066059847825d8a1f2/share/gap/lib/twocohom.gi:689 called from
<function "ConfluentMonoidPresentationForGroup">( <arguments> )
 called from read-eval loop at *stdin*:1
```

I tried:
```julia
function rules(G)
  X = GAP.Globals.IsomorphismFpGroupByGenerators(G.X, GAP.Globals.GeneratorsOfGroup(G.X))
  X = GAP.Globals.Range(X)
  C = GAP.Globals.ConfluentMonoidPresentationForGroup(X)
  return C
end
```

on `G = cyclic_group(4)`. It worked on `G = symmetric_group(3)`

**Comment by fieker** [comment]
PS.: it also fails on Alt(5)

**Comment by fieker** [comment]
Quite possibly it just odes not work on Fp-Groups. I can call it directly on GrpPerm, however, then it chooses different generators.

**Comment by ThomasBreuer** [comment]
As far as I see, the fact that `G = symmetric_group(3)` works is just due to a special treatment of symmetric groups.
For other groups, either GAP will insist in the freedom to choose a suitable list of generators (for permutation groups), or one runs into an error because of a missing method (for `IsomorphismFpGroupByChiefSeries` in the case of an f.p. group).
Trying the GAP master branch yields essentially the same, except that the output format of `ConfluentMonoidPresentationForGroup` has changed from a list to a record. (Well, the function is not documented, so there is no reason to complain.)
Anyway, this is not an issue for GAP.jl but for GAP.
