### ISSUE TITLE
Tab completion in GAP for `Julia.XXX` does not work

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#795]
I thought we had this, but at least in the current version, this doesn't work

**Comment by ThomasBreuer** [comment]
In a plain Julia session, entering `sq` and hitting TAB completes to `sqrt`.
In Julia with GAP.jl, I call `GAP.prompt()` and enter first `Julia.Main.sq` and then TAB, and no completion is shown; entering another TAB yields a list of completions which does not contain `sqrt`.
(More precisely, `sqrt` is in the list only if `Julia.Main.sqrt` had been accessed earlier in the session.)

The GAP function that handles the completion is `GAPInfo.CommandLineEditFunctions.Functions.Completion`.
As far as I see, the problem is that GAP searches for a record component by comparing the given prefix with the entries in the list `ALL_RNAMES()`, and that this list knows only about GAP's record components, not about Julia variables.

One possibility to provide the missing functionality would be to introduce a `Completion` operation in GAP that takes an object and a prefix (and perhaps more) as its arguments, and to change `GAPInfo.CommandLineEditFunctions.Functions.Completion` such that the input `Julia.Main.sq` gets translated to a call of `Completion( Julia, "Main.sq" )` or `Completion( Julia.Main, "sq" )`, for which JuliaInterface can install a suitable method.

Of course we could also modify `GAPInfo.CommandLineEditFunctions.Functions.Completion` when JuliaInterface gets loaded, but I think this would be only a hack.

Perhaps @frankluebeck (who wrote the GAP command line editing stuff) has a better idea.

**Comment by fingolfin** [comment]
Actually I think it does work when using the latest (unreleased) GAP.jl.

Indeed, tab completion in GAP is implement for objects in the filters `IsRecord` and `IsComponentObjectRep`. And we use `RecNames` to tab complete.

Our `TheTypeOfJuliaModules` objects are `IsComponentObjectRep` records -- and we implement `RecNames` (in addition to the methods for `\.`, `\.\:\=`, `IsBound\.`, `Unbind\.`.

Indeed, with latest GAP.jl master, entering `Julia.sq` into a GAP prompt and then pressing `TAB` completes it to `Julia.sqrt` to me.

I think this is because a newer GAP_jll is used in `master`... 

So getting GAP.jl 0.8.0 released should be a priority. I'd really like to have PR #777 ready for that first, though... Of course also #726 would be good *sigh*

**Comment by fingolfin** [comment]
To expand on what I wrote: I made changes to the tab completion code in GAP specifically to support some of this; I wrote this issue because I noticed while working in Oscar that it didn't work after all -- but what I didn't realize is that Oscar is using a slightly outdated GAP.jl version...

So we can probably close this after all...

**Comment by ThomasBreuer** [comment]
@fingolfin I can confirm that this completion works if the newest version of GAP_jll i.s used
(I had made my tests with GAP.jl master, but somehow it was necessary to call `Pkg.update()` in order to force a newer version of GAP_jll.)

**Comment by fingolfin** [comment]
Fixed in 0.8.0
