### ISSUE TITLE
Update `GAP_pkg_juliainterface` for latest Julia 1.9

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#801]
In tests against Julia nightly, we now get an error `undefined symbol: jl_set_global`. That probably means we need to update `libjulia_jll` and then rebuild `GAP_pkg_juliainterface`.

**Comment by ThomasBreuer** [comment]
I had thought that we can solve this problem by providing a GAP function `JuliaSetVal` that calls `setglobal!` if this is available, and calls `ccall(:jl_set_global, ...)` otherwise.
However, this seems to be tricky.
All combinations of GAP code and Julia code which I tried end up in a crash of Julia 1.6.5 or Julia 1.9.0-DEV, depending on which one had precompiled GAP.jl before.
I understand that the code that decides which variant shall be used cannot be precompiled.
Trying to define the Julia function in question inside the `__init__` function of GAP.jl was not successful.
Making the decision at runtime in GAP code does not work because I cannot call `ccall` from GAP: `ccall` is a keyword not a function.
(Well, using `JuliaEvalString` *would* work, if one binds the intended value to some global GAP variable in advance. Is this perhaps the simplest solution?)

**Comment by fingolfin** [comment]
> crashing [...] depending on which one had precompiled GAP.jl before.

This sounds like issue #691. It would go away once we update the JLL to match any changes we may make in the C sources of JuliaInterface. However, we should also try to fix it "properly", as this is of course highly annoying.

If my guess is right, then to fix the crashes you "just" need to delete the compiled version of JuliaInterface before switching to another Julia version. In other words: your code may have been perfectly fine, the problem is in the compiled C code.

That said, it is difficult to say what exactly is the problem without seeing the code. So feel free to open a draft PR with what you have, and we can then discuss more there.

**Comment by fingolfin** [comment]
Resolve by #811
